# Generated by Django 5.0.2 on 2024-02-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_alter_cms_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cms",
            name="number",
            field=models.IntegerField(),
        ),
    ]
